complete 06-Get-commentsByID
moskgit/News-API pull request #6
Opened 2023-06-28 10:46 UTC by moskgit

This will complete 06 comments by article id

2023-06-28 11:15 UTC, yalicee requested changes
add a test: 
Status 200, valid ID, but has no comments responds with an empty array of comments

2023-06-29 07:46 UTC, moskgit commented
I've now refactored to add the requested test. But, I have a confusion. The requested test is asking me to write 'Status 200, valid ID, but has no comments responds with an empty array of comments' 
I previously wrote '404 Not Found' for the same. 
I'm unable to do both at the same time. 
Therefore, I skipped the last '404' test. Please clarify or let me know if there's a way to get both passed at the same time.
Thank you.

2023-06-29 09:00 UTC, johnhutcheon requested changes
Hi Mohsin, thanks for adding the extra 200 test. There is a way to get both this and the 404 test to pass. Think of how you can do an extra check to see if the article exists in another function. If you get stuck, drop us an nchelp 🙂

2023-06-29 15:26 UTC, roisinoreilly approved these changes
nicely refactored, PR approved :)

2023-06-29 15:26 UTC, roisinoreilly commented on models.js
> +        function checkWhatsGivingEmptyArray(article_id) {
this variable name could be a little bit clearer

2023-06-29 16:28 UTC, merged